export const data = [
  {
    name: "Easy Logo",
    link: "https://easy-logo.vercel.app/",
    github: "https://github.com/MohdFahad1/easy-logo",
    desc: "A full-stack logo maker application to easily craft unique logos with speed and simplicity.",
    tech: [
      "Next.js",
      "Tailwind CSS",
      "Context API",
      "Clerk",
      "MongoDB",
      "shadcn/ui",
    ],
    image: "/images/easylogo.png",
  },

  {
    name: "BudgetBuddy",
    link: "https://budgett-buddy.vercel.app/",
    github: "https://github.com/MohdFahad1/expense-tracker",
    desc: "A fullstack budget/expense tracker application to manage and control your expenses.",
    tech: [
      "Next.js",
      "Tailwind CSS",
      "Context API",
      "Recharts",
      "JWT",
      "MongoDB",
      "shadcn/ui",
    ],
    image: "/images/budgetbuddy.png",
  },
  {
    name: "ImageFix.io",
    link: "https://image-fix-io.vercel.app/",
    github: "https://github.com/MohdFahad1/restore-photos",
    desc: "Imagefix.io a full stack image restoration application which restore old photos using Cloudinary AI for free.",
    tech: ["Next.js", "Tailwind CSS", "Next Auth", "MongoDB", "Cloudinary AI"],
    image: "/images/imagefix.png",
  },
  {
    name: "Pixabay Clone",
    link: "https://react-pixabay-clone.netlify.app/",
    github: "https://github.com/MohdFahad1/pixabay-clone",
    desc: "Clone of the famous image searching web application Pixabay.",
    tech: ["React.js", "CSS", "Pixabay API"],
    image: "/images/pixabay.png",
  },
];
